=== Armaklan/geckos/src/js/json/template.schema.json
{
    "$schema": "http://json-schema.org/schema#",
    "description": "Validation Schema for the Templates in Geckos",
    "title": "Geckos' Templates",
    "type":"object",
    "properties":
    {
        "styles":
        {
            "type":"array",
            "minItems": 1,
            "items":
            {
                "type":"object",
                "title": "Style",
                "description": "A style to use in the template",
                "properties":
                {
                    "key": { "type":"string" },
                    "basedOn": { "type":"string" },
                    "isDefault": { "type": "boolean" },
                    "name": { "type":"string" },
                    "description": { "type":"string" },
                    "canvasBackground": { "type": "string", "pattern": "^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$" },
                    "canvasWidth": { "type": "integer", "minimum": 10 },
                    "canvasHeight": { "type": "integer", "minimum": 10 },
                    "fields":
                    {
                        "type":"array",
                        "minItems": 1,
                        "items":
                        {
                            "type":"object",
                            "properties":
                            {
                                "name":{ "type":"string", "pattern": "^[a-zA-Z_0-9]+$" },
                                "ignored":{ "type":"boolean" },
                                "label": { "type": "string" },
                                "default": { "type": ["string", "boolean", "number"]},
                                "type":
                                {
                                    "type": "string",
                                    "enum": [ "richtext", "multiline", "checkbox", "color", "image", "number", "options", "text"]
                                },
                                "options": { "$ref": "#/definitions/options" },
                                "sharedOptions": { "type": "string" }
                            },
                            "required": [ "name" ]
                        }
                    },
                    "canvasFields":
                    {
                        "type":"array",
                        "items":{
                            "type":"object"
                        }
                    }
                },
                "required": [ "key", "name" ]
            }
        },
        "fonts":
        {
            "type":"array",
            "items":{
                "type":"object",
                "properties":{
                    "fontFamily":{ "type":"string" },
                    "src":{ "type":"string", "format": "uri" },
                    "fontStyle":
                    {
                        "type":"string",
                        "enum": [ "italic", "normal" ]
                    }
                },
                "required":[
                    "fontFamily",
                    "src"
                ]
            }
        },
        "description":
        {
            "type":"object",
            "properties":
            {
                "description":{ "type":"string" },
                "title":{ "type":"string" },
                "credits":{ "type":"string" },
                "url":{ "type":"string", "format": "uri" },
                "logo": { "logo": "string", "format": "uri" }
            },
            "required": [ "description", "title" ]
        },
        "sharedOptions":
        {
            "type": "array",
            "items":
            {
                "type": "object",
                "properties":
                {
                    "key": { "type": "string" },
                    "options": { "$ref": "#/definitions/options" }
                },
                "required": [ "key", "options" ]
            }
        }
    },
    "required":[
        "styles",
        "description"
    ],
    "definitions": {
        "options":
        {
            "type": "array",
            "minItems": 1,
            "items":
            {
                "type": "object",
                "oneOf":
                [
                    {
                        "properties":
                        {
                           "option": { "type": [ "string", "integer" ] },
                           "text": { "type": "string" }
                        },
                        "required": ["option", "text"]
                    },
                    {
                        "properties":
                        {
                           "colorValue": { "type": "string", "pattern": "^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$" },
                           "text": { "type": "string" }
                        },
                        "required": ["colorValue", "text"]
                    }
                ]
            }
        }
    }
}

=== Armaklan/geckos/js/templates/pulpalley-charactercard.json
{
  "fonts":[
    {
      "fontFamily":"Rokkitt",
      "src":"https://fonts.gstatic.com/s/rokkitt/v10/Uu8b3yBtxQPmPTMr0WQ_CA.woff2"
    }
  ],
  "sharedOptions":[
    {
      "key":"characterType",
      "options":[
        {
          "option":"leader",
          "text":"Leader"
        },
        {
          "option":"sidekick",
          "text":"Sidekick"
        },
        {
          "option":"ally",
          "text":"Ally"
        },
        {
          "option":"follower",
          "text":"Follower"
        },
        {
          "option":"terror",
          "text":"Terror"
        },
        {
          "option":"gang",
          "text":"Gang"
        }
      ]
    },
    {
      "key":"characterType_fr",
      "options":[
        {
          "option":"leader",
          "text":"Meneur"
        },
        {
          "option":"sidekick",
          "text":"Disciple"
        },
        {
          "option":"ally",
          "text":"Allié"
        },
        {
          "option":"follower",
          "text":"Suiveur"
        },
        {
          "option":"terror",
          "text":"Terreur"
        },
        {
          "option":"gang",
          "text":"Gang"
        }
      ]
    },
    {
      "key":"healthDice",
      "options":[
        {
          "option":"d6*",
          "text":"d6*"
        },
        {
          "option":"d6",
          "text":"d6"
        },
        {
          "option":"d8",
          "text":"d8"
        },
        {
          "option":"d10",
          "text":"d10"
        },
        {
          "option":"d12",
          "text":"d12"
        }
      ]
    }
  ],
  "styles":[
    {
      "key":"classic",
      "name":"Classic template",
      "description":"The classic template for Pulp Alley.",
      "isDefault":false,
      "fields":[
        {
          "name":"name",
          "label":"Name",
          "default":"Captain Wolf"
        },
        {
          "name":"brawl",
          "label":"Brawl",
          "default":"3d10"
        },
        {
          "name":"shoot",
          "label":"Shoot",
          "default":"3d10"
        },
        {
          "name":"dodge",
          "label":"Dodge",
          "default":"2d8"
        },
        {
          "name":"might",
          "label":"Might",
          "default":"3d10"
        },
        {
          "name":"finesse",
          "label":"Finesse",
          "default":"2d8"
        },
        {
          "name":"cunning",
          "label":"Cunning",
          "default":"3d10"
        },
        {
          "name":"description",
          "label":"Description",
          "default":"...",
          "type":"richtext"
        },
        {
          "name":"characterType",
          "label":"Type",
          "type":"options",
          "default":"leader",
          "sharedOptions":"characterType"
        },
        {
          "name":"portray",
          "label":"Miniature's image",
          "type":"image",
          "ratio": 0.7142
        },
        {
          "name":"health",
          "label":"Health",
          "type":"options",
          "default":"d10",
          "sharedOptions":"healthDice"
        }
      ],
      "canvasFields":[
        {
          "id":"fullBox",
          "type":"rect",
          "width":350,
          "height":495,
          "fill":"#CAAB7F"
        },
        {
          "id":"name",
          "type":"textbox",
          "text":"$characterType$ : $name$",
          "fontSize":22,
          "styles":"££$characterType$ : **$name$**",
          "width":346,
          "top":2,
          "left":2
        },
        {
          "id":"combatBox",
          "type":"rect",
          "width":170,
          "height":106,
          "left":165,
          "top":36,
          "fill":"#E07B4F",
          "stroke":"#FFDDAA"
        },
        {
          "id":"skillsBox",
          "type":"rect",
          "width":170,
          "height":106,
          "left":165,
          "top":146,
          "fill":"#ACA497",
          "stroke":"#FFFFAA"
        },
        {
          "id":"brawlLabel",
          "type":"text",
          "text":"Brawl",
          "fontSize":22,
          "fontWeight":"bold",
          "left":175,
          "top":39
        },
        {
          "id":"shootLabel",
          "type":"text",
          "text":"Shoot",
          "fontSize":22,
          "fontWeight":"bold",
          "left":175,
          "top":74
        },
        {
          "id":"dodgeLabel",
          "type":"text",
          "text":"Dodge",
          "fontSize":22,
          "fontWeight":"bold",
          "left":175,
          "top":109
        },
        {
          "id":"mightLabel",
          "type":"text",
          "text":"Might",
          "fontSize":22,
          "fontWeight":"bold",
          "left":175,
          "top":149
        },
        {
          "id":"finesseLabel",
          "type":"text",
          "text":"Finesse",
          "fontSize":22,
          "fontWeight":"bold",
          "left":175,
          "top":184
        },
        {
          "id":"cunningLabel",
          "type":"text",
          "text":"Cunning",
          "fontSize":22,
          "fontWeight":"bold",
          "left":175,
          "top":219
        },
        {
          "id":"brawlValue",
          "type":"text",
          "text":"$brawl",
          "fontSize":22,
          "fontWeight":"bold",
          "left":270,
          "top":39
        },
        {
          "id":"shootValue",
          "type":"text",
          "text":"$shoot",
          "fontSize":22,
          "fontWeight":"bold",
          "left":270,
          "top":74
        },
        {
          "id":"dodgeValue",
          "type":"text",
          "text":"$dodge",
          "fontSize":22,
          "fontWeight":"bold",
          "left":270,
          "top":109
        },
        {
          "id":"mightValue",
          "type":"text",
          "text":"$might",
          "fontSize":22,
          "fontWeight":"bold",
          "left":270,
          "top":149
        },
        {
          "id":"finesseValue",
          "type":"text",
          "text":"$finesse",
          "fontSize":22,
          "fontWeight":"bold",
          "left":270,
          "top":184
        },
        {
          "id":"cunningValue",
          "type":"text",
          "text":"$cunning",
          "fontSize":22,
          "fontWeight":"bold",
          "left":270,
          "top":219
        },
        {
          "id":"pictureBox",
          "type":"rect",
          "left":2,
          "width":156,
          "top":36,
          "height":216,
          "fill":"#DABD9E",
          "stroke":"#FFDDBB"
        },
        {
          "id":"portray",
          "type":"image",
          "left":6,
          "width":150,
          "top":40,
          "height":210,
          "src":"$portray"
        },
        {
          "id":"descriptionBox",
          "type":"rect",
          "width":336,
          "left":2,
          "top":256,
          "height":190,
          "fill":"#DABD9E",
          "stroke":"#FFDDBB"
        },
        {
          "id":"descriptionValue",
          "type":"textbox",
          "width":330,
          "left":5,
          "top":260,
          "fontSize":18,
          "text":"$description$",
          "styles":"£description"
        },
        {
          "id":"healthBox",
          "type":"rect",
          "height":40,
          "left":5,
          "top":450,
          "fill":"#B1E29E",
          "stroke":"#000000",
          "width":"{{value = 330; if (card[health] == 'd6*') { value = 167; } else if (card[health] == 'd6') { value = 209; } else if (card[health] == 'd8') { value = 251; } else if (card[health] == 'd10') { value = 293; } else if (card[health] == 'd12') { value = 330; }}}"
        },
        {
          "id":"healthLabel",
          "type":"textbox",
          "width":70,
          "left":8,
          "textAlign":"left",
          "top":460,
          "fontWeight":"bold",
          "fontSize":20,
          "text":"Health :"
        },
        {
          "id":"healthValue1",
          "type":"textbox",
          "width":42,
          "left":76,
          "textAlign":"center",
          "top":462,
          "fontWeight":"bold",
          "fontSize":16,
          "text":"$health$"
        },
        {
          "id":"healthValue2",
          "type":"textbox",
          "width":42,
          "left":118,
          "textAlign":"center",
          "top":462,
          "fontWeight":"bold",
          "fontSize":16,
          "text":"{{if (card[health] == 'd6*') { value = 'Out'; } else if (card[health] == 'd6') { value = 'Down'; } else if (card[health] == 'd8') { value = 'd6'; } else if (card[health] == 'd10') { value = 'd8'; } else if (card[health] == 'd12') { value = 'd10'; }}}"
        },
        {
          "id":"healthValue3",
          "type":"textbox",
          "width":42,
          "left":160,
          "textAlign":"center",
          "top":462,
          "fontWeight":"bold",
          "fontSize":16,
          "text":"{{if (card[health] == 'd6') { value = 'Out'; } else if (card[health] == 'd8') { value = 'Down'; } else if (card[health] == 'd10') { value = 'd6'; } else if (card[health] == 'd12') { value = 'd8'; }}}"
        },
        {
          "id":"healthValue4",
          "type":"textbox",
          "width":42,
          "left":202,
          "textAlign":"center",
          "top":462,
          "fontWeight":"bold",
          "fontSize":16,
          "text":"{{if (card[health] == 'd8') { value = 'Out'; } else if (card[health] == 'd10') { value = 'Down'; } else if (card[health] == 'd12') { value = 'd6'; }}}"
        },
        {
          "id":"healthValue5",
          "type":"textbox",
          "width":42,
          "left":244,
          "textAlign":"center",
          "top":462,
          "fontWeight":"bold",
          "fontSize":16,
          "text":"{{if (card[health] == 'd10') { value = 'Out'; } else if (card[health] == 'd12') { value = 'Down'; }}}"
